path_pdfs: 'data/01_raw/KTA AI Rechnungen/*.pdf'
path_auswertung: 'data/01_raw/Auswertung.XLSX'

train_size: 0.8
random_state: 42

ocr_config: '--oem 1 --psm 12'
max_page_numbers: 2

spacy_lang: de_core_news_md

# window size of tokens around matches
n_lefts: 10
n_rights: 4

perform_grid_search: False
n_jobs: -1

vectorizer:
  analyzer: 'char_wb'
  ngram_range: [1,5]
  max_df: 0.7
  min_df: 1
  strip_accents: unicode
  token_pattern: (?u)\b[^\d\W]{2,}\b
  use_idf: False
  binary: False
  sublinear_tf: True

classifier:
  n_estimators: 200
  max_features: 'sqrt'